services:
  my-blog:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-blog
    ports:
      - "5002:5000"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./build:/usr/share/nginx/html   
    depends_on:
      - my-blog
    restart: unless-stopped
      
      

